# Generated by Django 5.0.3 on 2024-03-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
